### ISSUE TITLE
garden-linux can not run in centos 6.5

### ISSUE THREAD

**Issue by HelloLin** [cloudfoundry-incubator/garden-linux#16]
hello, i deploy the garden-linux in centos6.5, i have upgrade the kernel to 3.10.5 to support aufs, but when i want to create containers i appear the error for:  clone: Invalid argument, when run the command ./bin/wshd --run ./run --lib ./lib --root /var/vcap/data/.../rootfs --title 'wshd:id' --userns enabled. i think it is the error of the libc, but i have upgrade the libc for 2.19. but it didnt work now. i dont know why, i hope you can help me. thank you .

**Comment by vito** [comment]
Seems like your kernel doesn't have user namespaces enabled. Does it work without --userns?

**Comment by HelloLin** [comment]
i have checked that centos 6.5 is support for namespace, but how i enable it ? i run wiht : ./bin/wshd --run ./run --lib ./lib --root /var/vcap/data/.../rootfs --title 'wshd:id' --userns disabled, but it get error : GARDEN_CGROUP_PATH: UNBOUND VARIABLE.

**Comment by tsaleh** [comment]
Hello, @HelloLin - Is this still an issue for you, or can I close this out?

**Comment by HelloLin** [comment]
thank you, you can close it, i have solve this question by change the system to ubuntu 14.04.

**Comment by HelloLin** [comment]
hello, now i run garden-linux in centos 7.1, the same error as before. when i run : ./bin/wshd --run ./run --lib ./lib --root /var/vcap/data/garden-linux/graph/vfs/dir/mvkn85959s5 --title 'wshd: mvkn85959s5' --userns enabled
    errno = 22
    clone: Invalid argument
    Aborted (core dumped)

the error is appear in this code(wshd.c)

/* Setup namespaces */
  flags |= CLONE_NEWIPC;
  flags |= CLONE_NEWNET;
  flags |= CLONE_NEWNS;
  flags |= CLONE_NEWPID;
  flags |= CLONE_NEWUTS;
  flags |= w->clone_flags;

  pid = clone(child_run, stack, flags, w);
  if (pid == -1) {
    perror("clone");
    abort();
  }

i delete "flags |= w->clone_flags;" then i didn‘t appear "Invalid argument", but new error shows. so i want to know what "w->clone_flags" means, is it diffient between ubuntu and centos? i hope you can help me . thank you .

**Comment by glyn** [comment]
The clone flags set up namespaces, like it says in the comment. You can read about Linux namespaces on the web.

garden-linux is useless without namespace support, so you need to ensure namespaces, and hence the clone flags, are supported by  your operating system.

**Comment by julz** [comment]
Just to add that that specific line is adding the CLONE_NEWUSER flag which enables user namespaces when the -userns flag is passed to wshd. This means user namespaces are not supported on your OS. You *may* be able to run privileged containers, but you will not be able to run unprivileged containers (which are highly recommended for untrusted rootfses). Iirc Diego uses privileged for CF apps and unprivileged for docker containers.

**Comment by goonzoid** [comment]
@HelloLin I'm going to close this since we're not currently providing support for centos. Hope that's ok!
