### ISSUE TITLE
Multiple networks  support for containers

### ISSUE THREAD

**Issue by tsjsdbd** [cloudfoundry-incubator/garden-linux#17]
hi,

we want add multiple networks support for garden containers, descripted [HERE](https://groups.google.com/a/cloudfoundry.org/forum/#!topic/vcap-dev/XW-xjHDJugc). the setup is quite sample.

obviously, we need the function in /netfence/network/configure.go for create bridge/evth and connect it with containers. and alse /netfence/network/subnets/subnets.go for manage the IP/Net resource for containers.

so how we modify the code for this purpose? we want to make the code change more compatible, if community interest in this feature in the future, we can post our PR.

Thanks

**Comment by glyn** [comment]
We want to simplify the netfence interface since it is currently over-generic. I'll prioritise that chore because it will benefit us and now we are aware of others going into that code, it will save pain all round.

The next step for you would be to fork garden-linux and create an environment in which you can run all the tests. Then you'll be in a position to add an integration test for your desired scenario and then drill down to unit tests and implementation as necessary. (This is probably obvious, but I mention it because it's our development process and *may* not be normal practice for you.)

See [the development guide](https://github.com/cloudfoundry-incubator/garden-linux/blob/master/docs/DEVELOPING.md) for how easily to run all the tests. There are a couple of issues in doing that at the moment: `fly` needs `garden` to be set to the commit before we renamed the API package from `api` to `garden` and to set up a local concourse, we currently have to do the following:
```
cd ~/workspace/concourse
mkdir tempDir
cd tempDir
vagrant init concourse/lite
vagrant up
```

/cc @vito @xoebus 

If you see gaps in our development information, please let us know!

**Comment by tsjsdbd** [comment]
thank you for descripting the development process, I will try to follow that when develop.

on the other hand, i want discuss the code detail about adding multiple network across Garden-linux. when finished the code, the network for containers may like this:
![image](https://cloud.githubusercontent.com/assets/7219402/6091203/a35f8572-aed9-11e4-9846-b0e239581adc.png)

and inside one Garden/VM, it looks like this:
![image](https://cloud.githubusercontent.com/assets/7219402/6090207/7987c232-aeac-11e4-8c9a-0a0fc8e02570.png)

 So the function in /netfence/network/configure.go for create bridge/evth and connect it with containers is pretty good for us, i'm sure we can reuse it directly. 

Also /netfence/network/subnets/subnets.go for manage the IP/Net resource for containers is good, but it manage IP/Net pool on each cell, if I need one IP pool be shared for all cell, how can I reuse the fence code as much as possible?

I know it's a little detail about the implement, about you know we don't want to modify garden code too much, otherwise, it will hard to maintain or synchronize with the wonderful Garden-linux repositry.

Thanks @vito @xoebus @glyn

**Comment by glyn** [comment]
We should have finished deleting all references to fences later today, so
that should make it easier to read the networking code.

On Sat, Feb 7, 2015 at 7:12 AM, tsjsdbd <notifications@github.com> wrote:

> thank you for descripting the development process, I will try to follow
> that when develop.
>
> on the other hand, i want discuss the code detail about adding multiple
> network across Garden-linux. when finished the code, the network for
> containers may like this:
> [image: image]
> <https://cloud.githubusercontent.com/assets/7219402/6091203/a35f8572-aed9-11e4-9846-b0e239581adc.png>
>
> and inside one Garden/VM, it looks like this:
> [image: image]
> <https://cloud.githubusercontent.com/assets/7219402/6090207/7987c232-aeac-11e4-8c9a-0a0fc8e02570.png>
>
> So the function in /netfence/network/configure.go for create bridge/evth
> and connect it with containers is pretty good for us, i'm sure we can reuse
> it directly.
>
> Also /netfence/network/subnets/subnets.go for manage the IP/Net resource
> for containers is good, but it manage IP/Net pool on each cell, if I need
> one IP pool be shared for all cell, how can I reuse the fence code as much
> as possible?
>
> I know it's a little detail about the implement, about you know we don't
> want to modify garden code too much, otherwise, it will hard to maintain or
> synchronize with the wonderful Garden-linux repositry.
>
> Thanks @vito <https://github.com/vito> @xoebus <https://github.com/xoebus>
> @glyn <https://github.com/glyn>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry-incubator/garden-linux/issues/17#issuecomment-73353410>
> .
>



-- 
Regards,
Glyn

**Comment by goonzoid** [comment]
I'm guessing from the silence that tsjsdbd was able to implement this, or doesn't need it any more.

Closing for now. If this comes up as a requirement again we can talk about it on vcap-dev.

**Comment by tsjsdbd** [comment]
Hi, in fact, we issue a proposal on community with design docs here:
[https://groups.google.com/a/cloudfoundry.org/forum/#!mydiscussions/vcap-dev/8Ue_0UHJbi0](https://groups.google.com/a/cloudfoundry.org/forum/#!mydiscussions/vcap-dev/8Ue_0UHJbi0)

and we are working on this, hope it will works good, but the code we modifed is quite arbitrary, so we need some discussion with you guys.(also the Garden code changes fast, we are based on 0.935)
