### ISSUE TITLE
why create a new Bridge for each container?

### ISSUE THREAD

**Issue by tsjsdbd** [cloudfoundry-incubator/garden-linux#18]
Hi @glyn 

I'm curious why create a new Bridge for each container in Garden? what's the benefit?

for container reachable from Host or to Host, there are many ways:
1. like Warden, just Veth in Host
2. like Docker, one Bridge for all containers
so what's the purpose for not useing this two method? Is there any designe documents i can follow?

Thanks

**Comment by glyn** [comment]
This came in with the introduction of support for multiple containers to share a subnet, which simplifies the network management for the user in that use case.
 
garden-linux creates a bridge per subnet (and does not avoid creating the bridge for a /30, although the bridge is not strictly necessary in that case). The benefit of a bridge per a subnet is that it consumes a single IP address (actually the highest valid IP address) from the subnet range and this allows the user to  choose container IP addresses without having to avoid multiple IPs allocated for the host sides of virtual ethernet  pairs. I hope that's clear.

I'm afraid there isn't any design documentation.

**Comment by tsjsdbd** [comment]
thanks @glyn 

Get it, one Bridge for a subnet, somewhat like Docker, but Docker only have one subnet in a Host, and Garden can have many subnet. right?

we found this by depoly Diego release use BOSH, it use subnet with /30 by default the, maybe your are right: in the default case, Brige is not necessary :-) 

And also, this match our network mode, which also need a Bridge for one subnet. 

But we have to resolve the IP assignment problem, because two subnet in different cell is connected. If use Garden IP assignment menthod, it will cause two container(in different cell) may have the same IP, because garden manage IP resource pool itself, and the pool on each cell is the same.

we may need a scheduler who can decide which IP can be used for a new container (like auctioneer as a commander). and the remain IP resource in the pool may stored in ETCD, so there can be not single problem. And also we want reuse the Fence code as much as possible.

any suggestion? Thanks very much

**Comment by glyn** [comment]
Right - garden-linux supports multiple subnets.

We are about to change the fence code to make the networking function
easier to understand/modify/reuse.

I'm not sure I understand your requirement, but currently it is not
possible for two containers on distinct instances of garden-linux to be in
the same subnet.

On Fri, Feb 6, 2015 at 10:01 AM, tsjsdbd <notifications@github.com> wrote:

> thanks @glyn <https://github.com/glyn>
>
> Get it, one Bridge for a subnet, somewhat like Docker, but Docker only
> have one subnet in a Host, and Garden can have many subnet. right?
>
> we found this by depoly Diego release use BOSH, it use subnet with /30 by
> default the, maybe your are right: in the default case, Brige is not
> necessary :-)
>
> And also, this match our network mode, which also need a Bridge for one
> subnet.
>
> But we have to resolve the IP assignment problem, because two subnet in
> different cell is connected. If use Garden IP assignment menthod, it will
> cause two container(in different cell) may have the same IP, because garden
> manage IP resource pool itself, and the pool on each cell is the same.
>
> we may need a scheduler who can decide which IP can be used for a new
> container (like auctioneer as a commander). and the remain IP resource in
> the pool may stored in ETCD, so there can be not single problem. And also
> we want reuse the Fence code as much as possible.
>
> any suggestion? Thanks very much
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry-incubator/garden-linux/issues/18#issuecomment-73213684>
> .
>



-- 
Regards,
Glyn

**Comment by tsjsdbd** [comment]
Hi @glyn 

I'm useing this net mode to Garden, this make two containers on distinct instances of garden-linux to be in the same subnet (consider four containers with green color in two VM, they are in the same subnet). so under the net mode, one subnet is spread over differents cell. And this make us face the IP assignment problem (one subnet's IP pool, need be shared for all cell)

![image](https://cloud.githubusercontent.com/assets/7219402/6090207/7987c232-aeac-11e4-8c9a-0a0fc8e02570.png)

**Comment by glyn** [comment]
We spoke to @onsi about this and there may be bigger issues if you are
reusing Diego and not just garden-linux.

On Sat, Feb 7, 2015 at 1:44 AM, tsjsdbd <notifications@github.com> wrote:

> Hi @glyn <https://github.com/glyn>
>
> I'm useing this net mode to Garden, this make two containers on distinct
> instances of garden-linux to be in the same subnet (consider four
> containers with green color in two VM, they are in the same subnet). so
> under the net mode, one subnet is spread over differents cell. And this
> make us face the IP assignment problem (one subnet's IP pool, need be
> shared for all cell)
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/7219402/6090207/7987c232-aeac-11e4-8c9a-0a0fc8e02570.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry-incubator/garden-linux/issues/18#issuecomment-73343756>
> .
>



-- 
Regards,
Glyn

**Comment by Katherine0801** [comment]
Could you explain the bigger issue if reusing Diego?
@glyn

**Comment by glyn** [comment]
I'm not a Diego expert, I'm afraid.
