### ISSUE TITLE
How garden fetch a private repository Docker image?

### ISSUE THREAD

**Issue by tsjsdbd** [cloudfoundry-incubator/garden-linux#22]
Hi, @vito @xoebus @glyn

can garden download an image from a private repository? means it need username&paaswords.

think about this scenario: if we have a Docker registry along with CF, and each CF user has his own repository, he can login Docker repository use CF username&passwords, and he want to deploy his private docker image. how to pass the Token to garden?(diego doesn't hold user information, only CC have it)

I see this code before fetch Image, it get Token from [RepoURL](https://github.com/cloudfoundry-incubator/garden-linux/blob/master/old/linux_backend/repository_fetcher/repository_fetcher.go#L107), so i think this make garden only support public repository, right?

So, how garden fetch a private repository Docker image? 

Thanks

**Comment by tsaleh** [comment]
Hi @tsjsdbd - Garden currently supports private registries ([here](https://www.pivotaltracker.com/story/show/88888066) and [here](https://www.pivotaltracker.com/story/show/77226688)), but not with authentication.    We have [a story in the icebox](https://www.pivotaltracker.com/n/projects/1158420/stories/87459112) to support this.
