### ISSUE TITLE
Question about insecureDockerRegistryList

### ISSUE THREAD

**Issue by shinji62** [cloudfoundry-incubator/garden-linux#23]
Hi,

I saw this flag on the code (old) insecureDockerRegistryList , there is anyway which we can provide this flag from CF or bosh deployment ?

Thanks

**Comment by georgethebeatle** [comment]
Hi @shinji62, currently there is no way to allow insecure docker registries. You have to secure your registry or use the public docker hub. We are currently working on enabling such integration. Can you share your use case?

**Comment by shinji62** [comment]
Basically local deployment with bosh-lite, using my local repos, I was thinking about the options in diego-release https://github.com/cloudfoundry-incubator/diego-release/blob/develop/jobs/garden-linux/templates/garden-linux_ctl.erb as this options exist https://github.com/cloudfoundry-incubator/garden-linux-release/blob/master/jobs/garden/templates/garden_ctl.erb#L84-L86

But I am not sure diego will consume such options.

**Comment by LaynePeng** [comment]
I found even parameter insecureDockerRegistryList being send to garden-linux, it won't be call.And I have another question, what is meaning the folder "old"? Will it to replace entirely later?

**Comment by georgethebeatle** [comment]
Yes, garden-linux accepts that parameter, but this is not enough if you want to stage and run a docker image from a private repo. At least you have to make the stager trust your private repo as well. That's part of what we're doing. For now you have to use the docker hub or secure your private registry with a self-signed certificate.

**Comment by tsaleh** [comment]
Hey, all - I'm going to close this issue, as it's not actually related to Garden.  @onsi Where is the right place for this conversation?  https://github.com/cloudfoundry-incubator/diego-release?
