### ISSUE TITLE
Garden-linux to understand poxy

### ISSUE THREAD

**Issue by dhilipkumars** [cloudfoundry-incubator/garden-linux#24]
Hi All

I'm trying to setup lattice at my work environment.  I'm behind a corporate proxy so garden-linux is unable to download docker images.  

```
[logs] 24 Mar 02:10 [garden-linux|lattice-cell-01] {"timestamp":"1427177426.772569895","source":"garden-linux","message":"garden-linux.pool.j88ebebafn8.create-rootfs.failed-to-fetch","log_level":2,"data":{"attempt":2,"error":"Get https://index.docker.io/v1/repositories/cloudfoundry/lattice-app/images: dial tcp 162.242.195.84:443: connection timed out","of":3,"session":"2.226.1"}}
```
The proxy settings works from within that Vagrant box (VM). 

```
$time curl https://index.docker.io/v1/repositories/cloudfoundry/lattice-app/images
[{"checksum": "", "id": "d7b54f2e72f1f93c7362a984458ff007906c704c522f20cb980318d2648cece4"}, {"checksum": "", "id": "b27d3cc7b2c55295051a992b0da815af8eae1e8f1045ed9871389df34cd77432"}, {"checksum": "", "id": "29d531509fb1a8c6592643d2ed20882ea77ff04a9f3691b5eb5e91ec4468c50d"}, {"checksum": "", "id": "ab18e115d7440026f4ac4081d89f1325a7408460db512ca48c6de6cecc744ef9"}, {"checksum": "", "id": "5df4437d2e8c2ce957958dc2704784a9bb65b78c9f51c70b6ef7c6d688cecd9a"}, {"checksum": "", "id": "398081adea6bc20de2000eebaf4c858a653dae94fa1b0905dfbca6080378f1d7"}, {"checksum": "", "id": "f836b582908834f53e3c06b1bb4e7757ddcd09119ac3a32666d14e73f0645e46"}, {"checksum": "", "id": "23b6fd800750cd75309ce463f23b033e073cf6a8bbd663c665f06ca0ea3ecdf3"}, {"checksum": "", "id": "894fd61c3e126b7266bd79a33d2ec9eb51d5b5fc255d27c2a0bcaa64495e1e3d"}, {"checksum": "", "id": "765b72bbb48506cc0e963d972b2ad1f5203df7cd0577f192d804cafb5000b7b8"}, {"checksum": "", "id": "e9707edecc492141d0f382278d651976ba07cb29eedae8a9d41f693e979b73dd"}, {"checksum": "", "id": "4a138b3e236e63b77b41f46f655f5927822a508da384f40aecd3825f2917b5ea"}, {"checksum": "", "id": "d940f6fef5912748063c2de1b8b4c39d7276ae15f4b7bd22018b6e5d7ea8a711"}, {"checksum": "", "id": "25fb2184d4afbb495e9ae02a677831345b0803ba92e4d88a5f50aab60a85d27e"}, {"checksum": "", "id": "df7546f9f060a2268024c8a230d8639878585defcc1bc6f79d2728a13957871b"}, {"checksum": "", "id": "511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158"}]
real    0m1.527s
user    0m0.012s
sys     0m0.012s
```

 Is there a way we can configure garden-linux pick up these http & https proxy settings ?

**Comment by dhilipkumars** [comment]
Hello Team,

Have a quick question.  Garden linux picks up environment variables set in 

```
$cat /var/lattice/setup/lattice-environment
CONSUL_SERVER_IP=192.168.11.11
SYSTEM_DOMAIN=192.168.11.11.xip.io
LATTICE_CELL_ID=lattice-cell-01
GARDEN_EXTERNAL_IP=192.168.11.11
CONSUL_SERVER_IP=192.168.11.11
SYSTEM_DOMAIN=192.168.11.11.xip.io
LATTICE_CELL_ID=lattice-cell-01
GARDEN_EXTERNAL_IP=192.168.11.11
HTTPS_PROXY=https://porxy_host:port
https_proxy=https://porxy_host:port
HTTP_PROXY=http://porxy_host:port
http_proxy=http://porxy_host:port
```

which helps me move on from "dial timeout" error but fails here.  

```
02 Apr 03:19 [garden-linux|lattice-cell-01] {"timestamp":"1427959183.051491737","source":"garden-linux","message":"garden-linux.pool.k910h5co905.create-rootfs.fetch.using-cached","log_level":1,"data":{"layer":"29d531509fb1a8c6592643d2ed20882ea77ff04a9f3691b5eb5e91ec4468c50d","repo":{"Scheme":"docker","Opaque":"","User":null,"Host":"","Path":"/cloudfoundry/lattice-app","RawQuery":"","Fragment":"latest"},"session":"2.9.1.1","tag":"latest"}}
.
.
.
02 Apr 03:19 [garden-linux|lattice-cell-01] time="2015-04-02T07:19:52Z" level="error" msg="[warning]: couldn't run auplink before unmount: exec: \"auplink\": executable file not found in $PATH"
02 Apr 03:19 [garden-linux|lattice-cell-01] {"timestamp":"1427959192.989367485","source":"garden-linux","message":"garden-linux.pool.destroy.destroyed","log_level":1,"data":{"id":"k910h5co905","session":"2.10"}}
```

but when i simply hardcode using os.Setenv("http://proxyhost:port") my proxy in old/main.go things work perfectly well.  I'm able to download images without any problem.   will it be a good idea to add a command line option to garden-linux that takes proxy variables? 

This is really a showstopper for us. :-(  Any help would great.

**Comment by vito** [comment]
I may be misreading but that auplink error is just a warning (which
unfortunately there is no way to silence). Is something still not working?

**Comment by dhilipkumars** [comment]
@vito Thanks for the response.   
When i set up proxy variables via  /var/lattice/setup/lattice-environment and vagrant reload, i do not get 
```
dial tcp 162.242.195.84:443: connection timed out"
```
the original error, but i get 
```
garden-linux.pool.k910h5co905.create-rootfs.fetch.using-cached" (probably not an error)
.
.
and
.
.
nmount: exec: \"auplink\": executable file not found in $PATH"  
```
and eventually apps dont come up, but when i revert that change in 'lattice-environment', simply (just as a test) hardcode
```
line 226
if len(*tag) > 2 {
		println("-tag parameter must be less than 3 characters long")
		println()
		flag.Usage()
		return
	}
os.Setenv("http_proxy", "http://myproxyport")  
```
in 'old/main.go' and 'vagrant reload' the apps are downloaded properly and they come up.   I also do not notice any auplink error that time.  Any clues?

**Comment by goonzoid** [comment]
@dhilipkumars Did you ever reach any kind of solution on this?

I'm not very familiar with how lattice runs garden-linux, so no idea how the contents of `/var/lattice/setup/lattice-environment` makes it into the garden-linux env. Could be an issue on the Lattice end.

**Comment by dhilipkumars** [comment]
@goonzoid 
Sorry for the delayed response.  I had stopped keeping track of this issue.  The only way i was able to resolve this error is by setting proxy settings inside garden-linux

```
os.Setenv("http_proxy", "http://myproxy:port")  
```

something like above...in the main function.  rebuild garden-linux and deploy it again inside the vm. 
 I will close this issue now as i do not have enough evidence that this is a garden-linux related problem.

**Comment by bonzofenix** [comment]
I Do think there should be a way to tell garde-linux and its containers to set http_proxy and https_proxy. Is there anything in the backlog on this?

**Comment by goonzoid** [comment]
@bonzofenix The way to do this is to set `HTTP_PROXY` or `HTTPS_PROXY` environment variables. If you're using the BOSH release then there's a [pull request](https://github.com/cloudfoundry-incubator/garden-linux-release/pull/5) to expose these.
