### ISSUE TITLE
Development environment for garden-linux

### ISSUE THREAD

**Issue by shashidharatd** [cloudfoundry-incubator/garden-linux#25]
Hi,
  I am trying to setup a development environment for garden-linux and am confused with the instructions in README.md. There is one Vagrantfile (https://github.com/cloudfoundry-incubator/garden-linux/blob/master/Vagrantfile) in the garden-linux repo and the readme is pointing to setup another vagrant box in https://github.com/cf-guardian/dev/blob/master/Vagrantfile . which one should be followed. I would like to run the unit tests and integration tests of garden-linux. please point me to the right direction. appreciate your help.

Thanks
@shashidharatd

**Comment by tsaleh** [comment]
Hi @shashidharatd,

@glyn can comment on how they run their unit and integration tests.  I'm not sure if the `Vagrantfile` in this repo is used for anything.

**Comment by shashidharatd** [comment]
Thanks a lot @tsaleh,
  Your suggestion helped. hoping @glyn can also give some insights to this.

Thanks
@shashidharatd

**Comment by glyn** [comment]
Although we are working on a [vagrant test environment](https://www.pivotaltracker.com/story/show/90623496) without nested containers, our current testing approach is to set up a [concourse](http://concourse.ci/) instance and then use `scripts/remote-fly` in the garden-linux repository to run all the unit and integration tests automatically under concourse. Please see the [instructions](http://concourse.ci/deploying-with-vagrant.html) on setting concourse up under vagrant to get started.

**Comment by shashidharatd** [comment]
Hi @glyn,
  I was able to bring up concourse ci in vagrant and then was able to run the tests by calling `scripts/garden-fly`. Thanks for the clarification.

I have one more issue. is it possible to work with rootfs without docker url in build.yml. I am trying to extract and give the rootfs [lucid64.dev.tgz](http://cf-runtime-stacks.s3.amazonaws.com/lucid64.dev.tgz), but i couldn't succeed. probably because garden is running within a container. so at this moment is it possible at all to use rootfs from non-docker url's to run the tests?

Thanks once again.

**Comment by glyn** [comment]
I don't see why that shouldn't be possible, but maybe the vagrant test environment will get you there faster if you can wait a day or two until this is available.

**Comment by julz** [comment]
The build.yml is used by fly and I *think* it only supports docker rootfses (although it uses garden to run them). Using a non-docker rootfs would be a feature request for fly/concourse so you may want to ask there. Note that in either case (whether you specify a docker url or a rootfs) you'd be running in a garden container. 

Out of interest, why do you want to run the tests with a  rootfs rather than a docker url? Many of the tests assume they'll run inside our warden-ci docker image which has some prebuilt rootfses included in it for tests to use so using something like lucid64 would cause a fair few tests to be skipped.

**Comment by shashidharatd** [comment]
Hi @julz,
  My environment is behind a corporate web proxy and the connection gets timed out while using docker url. so was trying a workaround to use the downloaded rootfs. now things are little clear, so will try and fix the connection timeout issues with docker url in my environment.

Thanks for suggestion
@shashidharatd

**Comment by goonzoid** [comment]
Looks like this is resolved.
