### ISSUE TITLE
Docker creates the WORKDIR if it doesn't already exist.  Garden does not.

### ISSUE THREAD

**Issue by onsi** [cloudfoundry-incubator/garden-linux#29]
This is coming out an issue surfaced in Lattice:
https://github.com/cloudfoundry-incubator/lattice/issues/66

When spinning up a Docker container Docker always creates the requested working directory (whether it is part of the Dockerfile WORKDIR or specified via `docker run -w /foo`).  Garden-Linux does not reproduce this behavior and, as a result, Docker images that specify nonexisting WORKDIRs fail with `chdir: No such file or directory `.

The most straightforward path forward is probably to emulate Docker's behavior (and document it).  Thoughts?

**Comment by goonzoid** [comment]
Closing here since we have an issue in tracker with ongoing discussion.
