### ISSUE TITLE
Should add some additonal env to "setup.sh"

### ISSUE THREAD

**Issue by tsjsdbd** [cloudfoundry-incubator/garden-linux#30]
Hi,

Sometimes, we need to keep the container not be destroyed when debuging problems, login to container by `./bin/wsh`, after that we can destroy it manually.

But the `stop.sh` and the `destroy.sh` can not be run directly, because miss some env like `GARDEN_CGROUP_PATH` and `GARDEN_IPTABLES_NAT_PREROUTING_CHAIN`. notes that this two scripte can run directly in Warden.

So, it will be quite good to add all env which `stop.sh`, `destroy.sh`, `net.sh` will use into the `setup.sh` like [iface_name_prefix](https://github.com/cloudfoundry-incubator/garden-linux/blob/master/old/linux_backend/skeleton/setup.sh#L11).

This will make sense for mess around with Garden.
@lyuyun

Thanks

**Comment by tsaleh** [comment]
Hey @tsjsdbd - What kind of problems are you looking to debug, and how are you driving Garden?  I'd expect that you could `Create()` a container, `Run()` something inside it, and then ssh to the host and debug the issue via `wsh` before later calling `Destroy()`.  Why would you want to destroy the container via the `stop.sh` and `destroy.sh` scripts?

(also, we're going to be rewriting all of the shell scripts in Go, so this probably isn't the right time to add functionality to them)

**Comment by tsjsdbd** [comment]
Because we are behind the proxy (in a internal network), and always face network download problems,  also, in the Garden log, it is difficult to get the command stdout or stderr, it always said `command exited code 1`. So we need login to container use `wsh` to verfy if the command execute correct or see what's the real output, when use Diego intergrate with CF.

it's another thing that Garden's log should include the command's stdout and stderr when run command failed. just a exited code is not enough.

**Comment by goonzoid** [comment]
@tsjsdbd were you able to work around this in the end? I'd like to close this issue given that we're rewriting those scripts in Go now.

**Comment by tsjsdbd** [comment]
it is very difficult to get the script's error output from Garden's log when call these scripts, like start.sh. it's very useful if we can control Container lifecycle by these script seperately.(like Warden)
so i wonder if you can add this ENV before it become GO code, i believe it is very simple. or I can send a PR if it will be long time before it become GO. but if it already have GO implementation, please omit this, and just colse it. @goonzoid

**Comment by goonzoid** [comment]
@glyn Am I correct in thinking that `setup.sh` is going to be gone when we merge the wshd rewrite branch?

**Comment by glyn** [comment]
@goonzoid No, setup.sh will survive the wsh/wshd rewrite.

**Comment by goonzoid** [comment]
Since we'll soon stop supporting Garden-Linux in favour of [Guardian](https://github.com/cloudfoundry-incubator/guardian), I think we're unlikely to fix this.

@tsjsdbd please feel free to submit a PR if this is still an issue for you. Thanks.
