### ISSUE TITLE
Garden containers lack /etc/mtab

### ISSUE THREAD

**Issue by ephesused** [cloudfoundry-incubator/garden-linux#42]
Without /etc/mtab, df and certain monitoring processes (in my case, check_disk for nagios) report a failure since the filesystems cannot be found properly.  If it makes a difference, I tripped on this issue in lattice.

Thanks,
Ed

```
root@mah54ac9gbm:~# df
df: cannot read table of mounted file systems: No such file or directory
root@mah54ac9gbm:~# ls /etc/mtab
ls: cannot access /etc/mtab: No such file or directory
root@mah54ac9gbm:~# mount
none on / type aufs (rw,relatime,si=424c4f2352c59bd7)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=666)
none on /proc type proc (rw,relatime)
tmpfs on /dev/shm type tmpfs (rw,nodev,relatime)
root@mah54ac9gbm:~# df /
df: Warning: cannot read table of mounted file systems: No such file or directory
Filesystem     1K-blocks    Used Available Use% Mounted on
-               41251136 4693372  34849324  12% /
root@mah54ac9gbm:~# /usr/lib/nagios/plugins/check_disk -c 5% -w 10%
DISK UNKNOWN - free space:|
root@mah54ac9gbm:~# /usr/lib/nagios/plugins/check_disk -c 5% -w 10% -p /
DISK CRITICAL: / not found
root@mah54ac9gbm:~# grep -v rootfs /proc/mounts > /etc/mtab
root@mah54ac9gbm:~# df
Filesystem     1K-blocks    Used Available Use% Mounted on
none            41251136 4693508  34849188  12% /
tmpfs            2024148       0   2024148   0% /dev/shm
root@mah54ac9gbm:~# /usr/lib/nagios/plugins/check_disk -c 5% -w 10%
DISK OK - free space: / 34032 MB (88% inode=95%); /dev/shm 1976 MB (100% inode=99%);| /=4583MB;36255;38269;0;40284 /dev/shm=0MB;1778;1877;0;1976
root@mah54ac9gbm:~#
```

**Comment by goonzoid** [comment]
Hi @ephesused. Thanks for raising this. We have a plan for a fix, but it may be a little while before it makes it into master.

In the meantime we can suggest a workaround, which is to symlink `/etc/mtab` to `/proc/mounts` if `/etc/mtab` doesn't exist in your rootfs or docker image.

**Comment by goonzoid** [comment]
@ephesused Did you try the workaround? Were you able to get it to work?

**Comment by ephesused** [comment]
Sorry for the delay - yes, the workaround is good.  My use case is through lattice, and I don't know enough to apply the workaround through lattice other than shelling into one of the containers after the fact and manually applying the symlink.  That works just fine (see below).  I don't see a clean way to automate that process for every ltc create call.

For what it's worth, the symlink approach is how docker addressed it: https://github.com/docker/docker/issues/4064

root@njlp6h7j1eo:~# df
df: cannot read table of mounted file systems: No such file or directory
root@njlp6h7j1eo:~# /usr/lib/nagios/plugins/check_disk -c 5% -w 10%
DISK UNKNOWN - free space:|
root@njlp6h7j1eo:~# ls -l /etc/mtab
ls: cannot access /etc/mtab: No such file or directory
root@njlp6h7j1eo:~# ln -s /proc/mounts /etc/mtab
root@njlp6h7j1eo:~# df                                             
Filesystem     1K-blocks    Used Available Use% Mounted on
none            41251136 4762068  34780628  13% /
tmpfs            2024148       0   2024148   0% /dev/shm
root@njlp6h7j1eo:~# /usr/lib/nagios/plugins/check_disk -c 5% -w 10%
DISK OK - free space: / 33965 MB (87% inode=95%); /dev/shm 1976 MB (100% inode=99%);| /=4650MB;36255;38269;0;40284 /dev/shm=0MB;1778;1877;0;1976
root@njlp6h7j1eo:~#

**Comment by julz** [comment]
Hi @ephesused, one easy(ish!) way to use the workaround is to simply build your own docker image (from the base image you want to use) that contains the symlink. You could then push the modified image to your dockerhub account or to a private docker registry and push the modified image - which would contain the symlink - to lattice.
