### ISSUE TITLE
getpwnam: Invalid argument

### ISSUE THREAD

**Issue by mehtaphysical** [cloudfoundry-incubator/garden-linux#50]
I'm getting an error when trying to stream in. 

```
{"timestamp":"1441588907.862973928","source":"garden-linux","message":"garden-linux.stream-in.command.failed","log_level":2,"data":{"argv":["/var/vcap/data/garden/depot/0ccqo5skbsm/bin/nstar","1470","vcap","/tmp"],"error":"exit status 1","exit-status":1,"session":"45.1","stderr":"getpwnam: Invalid argument\n","stdout":"","took":"3.130479ms"}}
```

I'm trying to push a docker container using a lattice(ish) bosh-lite build. Not sure what this error is complaining about. vcap is a valid user. Also `getpwnam("vcap")` has no issues (although that only tests the glib version so...).

**Comment by julz** [comment]
Hi @mehtaphysical - I think we dropped the ball on this issue, sorry about that! Are you still having the above problem?
