### ISSUE TITLE
Garden-linux is how to deal with the docker images in the docker register-v1 and register-v2 coexistence problem, garden - Linux is migrated stored image on how the v1 to v2?

### ISSUE THREAD

**Issue by wdxxs2z** [cloudfoundry-incubator/garden-linux#51]

**Comment by goonzoid** [comment]
Hi @wdxxs2z. I'm having trouble parsing this. Do you think you could provide a more detailed explanation of the problem please?

**Comment by wdxxs2z** [comment]
Hi @goonzoid . I mean, if I used docker register is v1 before, now I started to use docker register v2, before the mirror stored in the v1. What should I do

**Comment by goonzoid** [comment]
I'm afraid I'm still not quite sure what the problem is. Perhaps you could provide some reproduction steps for the issue?
