### ISSUE TITLE
When i push docker app,the docker images layer can download,but failed to create container and start

### ISSUE THREAD

**Issue by wdxxs2z** [cloudfoundry-incubator/garden-linux#53]
cf version:223,diego version:v0.1440.0,garden version:0.326.0

bosh-lite-virtualbox-ubuntu-trusty-9000.69.0 

stemcell warden version : 2776

The error logs here:

    {
    "timestamp": "1447171347.288635492",
    "source": "garden-linux",
    "message": "garden-linux.container.start.command.failed",
    "log_level": 2,
    "data": {
        "argv": [
            "/var/vcap/data/garden/depot/5ao0fmhurdf/start.sh"
        ],
        "error": "exit status 2",
        "exit-status": 2,
        "handle": "fe49ba8e-d684-45a6-9d68-ff8da2d84efe-3f88d182-f4c5-49a1-b913-40b44d68eb02-d08042f1-c8a8-4748-5289-b2d1c0e631b4",
        "session": "207.1.1",
        "stderr": "Failed to create container: containerizer: wait for container: error: containerizer: initializing the container: system: mount sysfs on /sys: operation not permitted",
        "stdout": "",
        "took": "106.508642ms"
        }
    },
    {
    "timestamp": "1447171347.288709641",
    "source": "garden-linux",
    "message": "garden-linux.container.start.wshd-start-failed",
    "log_level": 2,
    "data": {
        "error": "exit status 2",
        "handle": "fe49ba8e-d684-45a6-9d68-ff8da2d84efe-3f88d182-f4c5-49a1-b913-40b44d68eb02-d08042f1-c8a8-4748-5289-b2d1c0e631b4",
        "session": "207.1"
    }
    },
    {
    "timestamp": "1447171341.902456522",
    "source": "garden-linux",
    "message": "garden-linux.5ao0fmhurdf.filter.logging-chain.command.failed",
    "log_level": 2,
    "data": {
        "argv": [
            "/sbin/iptables",
            "-w",
            "-X",
            "w--instance-5ao0fmhurdf-log"
        ],
        "error": "exit status 1",
        "exit-status": 1,
        "name": "w--instance-5ao0fmhurdf",
        "session": "205.1.1.4",
        "stderr": "iptables: No chain/target/match by that name.\n",
        "stdout": "",
        "took": "1.692442ms",
        "useKernelLogging": true
    }
    },
    {
    "timestamp": "1447171341.833693504",
    "source": "garden-linux",
    "message": "garden-linux.garden-server.create.failed",
    "log_level": 2,
    "data": {
        "error": "container: start: exit status 2",
        "request": {
            "Handle": "fe49ba8e-d684-45a6-9d68-ff8da2d84efe-3f88d182-f4c5-49a1-b913-40b44d68eb02-f4456f1a-81fa-4675-6568-a48f42d988b6",
            "GraceTime": 0,
            "RootFSPath": "docker:///tutum/tomcat#7.0",
            "BindMounts": null,
            "Network": "",
            "Privileged": false,
            "Limits": {
                "bandwidth_limits": {
                    
                },
                "cpu_limits": {
                    "limit_in_shares": 10
                },
                "disk_limits": {
                    "inode_hard": 200000,
                    "byte_hard": 1073741824
                },
                "memory_limits": {
                    "limit_in_bytes": 268435456
                }
            }
        },
        "session": "11.5581"
    }
    }
    }

The dmesg sub logs are:

		[ 2992.926171] WARNING: CPU: 2 PID: 23065 at /build/linux-lts-vivid-BZwsXG/linux-lts-vivid-3.19.0/net/sched/sch_generic.c:303 dev_watchdog+0x24f/0x260()
		[ 2992.926180] NETDEV WATCHDOG: eth0 (e1000): transmit queue 0 timed out
		[ 2992.926186] Modules linked in: ipt_MASQUERADE nf_nat_masquerade_ipv4 xt_comment ipt_REJECT nf_reject_ipv4 veth xt_nat iptable_nat nf_nat_ipv4 nf_nat nf_conntrack_ipv4 nf_defrag_ipv4 xt_conntrack nf_conntrack iptable_filter ip_tables x_tables aufs vboxsf(OE) dm_crypt ppdev iosf_mbi crct10dif_pclmul crc32_pclmul ghash_clmulni_intel aesni_intel aes_x86_64 lrw gf128mul glue_helper ablk_helper cryptd vboxvideo(OE) drm serio_raw i2c_piix4 vboxguest(OE) parport_pc 8250_fintek mac_hid lp parport video psmouse e1000 pata_acpi
		[ 2992.926282] CPU: 2 PID: 23065 Comm: monit Tainted: G           OE  3.19.0-26-generic #28~14.04.1-Ubuntu
		[ 2992.926316] Hardware name: innotek GmbH VirtualBox/VirtualBox, BIOS VirtualBox 12/01/2006
		[ 2992.926323]  ffffffff81b3f798 ffff88019fd03d58 ffffffff817aeed7 0000000000000000
		[ 2992.926331]  ffff88019fd03da8 ffff88019fd03d98 ffffffff81074d8a 0000000000000000
		[ 2992.926335]  0000000000000000 ffff880035d28000 0000000000000001 ffff880195f50880
		[ 2992.926357] Call Trace:
		[ 2992.926364]  <IRQ>  [<ffffffff817aeed7>] dump_stack+0x45/0x57
		[ 2992.926388]  [<ffffffff81074d8a>] warn_slowpath_common+0x8a/0xc0
		[ 2992.926398]  [<ffffffff81074e06>] warn_slowpath_fmt+0x46/0x50
		[ 2992.926415]  [<ffffffff816cce3f>] dev_watchdog+0x24f/0x260
		[ 2992.926429]  [<ffffffff816ccbf0>] ? dev_graft_qdisc+0x80/0x80
		[ 2992.926441]  [<ffffffff810dab89>] call_timer_fn+0x39/0x110
		[ 2992.926452]  [<ffffffff816ccbf0>] ? dev_graft_qdisc+0x80/0x80
		[ 2992.926464]  [<ffffffff810dc350>] run_timer_softirq+0x220/0x320
		[ 2992.926477]  [<ffffffff81078ee4>] __do_softirq+0xe4/0x270
		[ 2992.926523]  [<ffffffff810792ad>] irq_exit+0x9d/0xb0
		[ 2992.926537]  [<ffffffff817b990a>] smp_apic_timer_interrupt+0x4a/0x60
		[ 2992.926550]  [<ffffffff817b793d>] apic_timer_interrupt+0x6d/0x80
		[ 2992.926555]  <EOI>  [<ffffffff81203374>] ? __dentry_kill+0x154/0x1f0
		[ 2992.926575]  [<ffffffff8101df06>] ? native_read_tsc+0x6/0x20
		[ 2992.926586]  [<ffffffff8101df59>] read_tsc+0x9/0x10
		[ 2992.926599]  [<ffffffff810e2aee>] ktime_get_ts64+0x4e/0xf0
		[ 2992.926610]  [<ffffffff81200adc>] poll_select_set_timeout+0x5c/0x90
		[ 2992.926620]  [<ffffffff81201f16>] SyS_poll+0x56/0x100
		[ 2992.926629]  [<ffffffff817b688d>] system_call_fastpath+0x16/0x1b
		[ 2992.926653] ---[ end trace 4c3fd2fcc3107ad7 ]---
		[ 2992.926817] e1000 0000:00:03.0 eth0: Reset adapter
		[ 2992.997803] e1000: eth0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
		[ 3086.643323] EXT4-fs (loop5): mounted filesystem with ordered data mode. Opts: (null)
		[ 3086.645116] aufs test_add:245:garden-linux[8074]: unsupported filesystem, /tmp/docker-aufs-base087856446 (aufs)
		[ 3086.779507] bridge: automatic filtering via arp/ip/ip6tables has been deprecated. Update your scripts to load br_netfilter if you need this.
		[ 3088.432297] cgroup: mkdir (13065) created nested cgroup for controller "memory" which has incomplete hierarchy support. Nested cgroups may change behavior in the future.
		[ 3088.432300] cgroup: "memory" requires setting use_hierarchy to 1 on the root
		[ 3088.436395] IPv6: ADDRCONF(NETDEV_UP): w5c4ev84eb02-0: link is not ready
		[ 3088.436507] device w5c4ev84eb02-0 entered promiscuous mode
		[ 3088.482527] IPv6: ADDRCONF(NETDEV_CHANGE): w5c4ev84eb02-0: link becomes ready
		[ 3088.482562] wb-5c4ev84dv420: port 1(w5c4ev84eb02-0) entered forwarding state
		[ 3088.482570] wb-5c4ev84dv420: port 1(w5c4ev84eb02-0) entered forwarding state
		[ 3103.526164] wb-5c4ev84dv420: port 1(w5c4ev84eb02-0) entered forwarding state
		[ 3104.135422] wb-5c4ev84dv420: port 1(w5c4ev84eb02-0) entered disabled state
		[ 3104.135688] device w5c4ev84eb02-0 left promiscuous mode
		[ 3104.135704] wb-5c4ev84dv420: port 1(w5c4ev84eb02-0) entered disabled state
		[ 5527.586003] EXT4-fs (loop5): mounted filesystem with ordered data mode. Opts: (null)
		[ 5527.587589] aufs test_add:281:garden-linux[8071]: uid/gid/perm /var/vcap/data/garden/aufs_graph/aufs/diff/99700f858b57772ec5a1b106aba258913b42ee84a98a80f1fda68156804f1dbd 4294967294/4294967294/0755, 0/0/0755
		[ 5528.844983] IPv6: ADDRCONF(NETDEV_UP): w5c4ev84eb03-0: link is not ready
		[ 5528.845077] device w5c4ev84eb03-0 entered promiscuous mode
		[ 5528.901795] device w5c4ev84eb03-0 left promiscuous mode
		[ 5528.901820] wb-5c4ev84dv430: port 1(w5c4ev84eb03-0) entered disabled state
		[ 5537.957360] EXT4-fs (loop5): mounted filesystem with ordered data mode. Opts: (null)
		[ 5537.959900] aufs test_add:281:garden-linux[8071]: uid/gid/perm /var/vcap/data/garden/aufs_graph/aufs/diff/99700f858b57772ec5a1b106aba258913b42ee84a98a80f1fda68156804f1dbd 4294967294/4294967294/0755, 0/0/0755
		[ 5538.158069] IPv6: ADDRCONF(NETDEV_UP): w5c4ev84eb04-0: link is not ready
		[ 5538.158147] device w5c4ev84eb04-0 entered promiscuous mode
		[ 5538.224892] device w5c4ev84eb04-0 left promiscuous mode
		[ 5538.224907] wb-5c4ev84dv440: port 1(w5c4ev84eb04-0) entered disabled state
		[ 5547.777852] EXT4-fs (loop5): mounted filesystem with ordered data mode. Opts: (null)
		[ 5547.780411] aufs test_add:281:garden-linux[8072]: uid/gid/perm /var/vcap/data/garden/aufs_graph/aufs/diff/99700f858b57772ec5a1b106aba258913b42ee84a98a80f1fda68156804f1dbd 4294967294/4294967294/0755, 0/0/0755
		[ 5548.017589] IPv6: ADDRCONF(NETDEV_UP): w5c4ev84eb05-0: link is not ready
		[ 5548.017692] device w5c4ev84eb05-0 entered promiscuous mode
		[ 5548.074879] device w5c4ev84eb05-0 left promiscuous mode
		[ 5548.075336] wb-5c4ev84dv450: port 1(w5c4ev84eb05-0) entered disabled state
		[ 5613.818051] EXT4-fs (loop5): mounted filesystem with ordered data mode. Opts: (null)
		[ 5613.820008] aufs test_add:281:garden-linux[8071]: uid/gid/perm /var/vcap/data/garden/aufs_graph/aufs/diff/99700f858b57772ec5a1b106aba258913b42ee84a98a80f1fda68156804f1dbd 4294967294/4294967294/0755, 0/0/0755
		[ 5614.015695] IPv6: ADDRCONF(NETDEV_UP): w5c4ev84eb06-0: link is not ready
		[ 5614.015773] device w5c4ev84eb06-0 entered promiscuous mode
		[ 5614.077304] device w5c4ev84eb06-0 left promiscuous mode
		[ 5614.077328] wb-5c4ev84dv460: port 1(w5c4ev84eb06-0) entered disabled state
		[ 5711.198382] EXT4-fs (loop5): mounted filesystem with ordered data mode. Opts: (null)
		[ 5711.201334] aufs test_add:281:garden-linux[7733]: uid/gid/perm /var/vcap/data/garden/aufs_graph/aufs/diff/99700f858b57772ec5a1b106aba258913b42ee84a98a80f1fda68156804f1dbd 4294967294/4294967294/0755, 0/0/0755
		[ 5711.404147] IPv6: ADDRCONF(NETDEV_UP): w5c4ev84eb07-0: link is not ready
		[ 5711.404408] device w5c4ev84eb07-0 entered promiscuous mode
		[ 5711.475792] device w5c4ev84eb07-0 left promiscuous mode
		[ 5711.476010] wb-5c4ev84dv470: port 1(w5c4ev84eb07-0) entered disabled state
		[ 5878.121919] EXT4-fs (loop5): mounted filesystem with ordered data mode. Opts: (null)
		[ 5878.124005] aufs test_add:281:garden-linux[9565]: uid/gid/perm /var/vcap/data/garden/aufs_graph/aufs/diff/99700f858b57772ec5a1b106aba258913b42ee84a98a80f1fda68156804f1dbd 4294967294/4294967294/0755, 0/0/0755
		[ 5878.326712] IPv6: ADDRCONF(NETDEV_UP): w5c4ev84eb08-0: link is not ready
		[ 5878.326824] device w5c4ev84eb08-0 entered promiscuous mode
		[ 5878.368734] device w5c4ev84eb08-0 left promiscuous mode
		[ 5878.368747] wb-5c4ev84dv480: port 1(w5c4ev84eb08-0) entered disabled state
		[ 6156.329965] EXT4-fs (loop5): mounted filesystem with ordered data mode. Opts: (null)
		[ 6156.331655] aufs test_add:281:garden-linux[8073]: uid/gid/perm /var/vcap/data/garden/aufs_graph/aufs/diff/99700f858b57772ec5a1b106aba258913b42ee84a98a80f1fda68156804f1dbd 4294967294/4294967294/0755, 0/0/0755
		[ 6156.576894] IPv6: ADDRCONF(NETDEV_UP): w5c4ev84eb09-0: link is not ready
		[ 6156.577002] device w5c4ev84eb09-0 entered promiscuous mode
		[ 6156.653326] device w5c4ev84eb09-0 left promiscuous mode
		[ 6156.653340] wb-5c4ev84dv490: port 1(w5c4ev84eb09-0) entered disabled state
		[ 6670.176255] EXT4-fs (loop5): mounted filesystem with ordered data mode. Opts: (null)
		[ 6670.178157] aufs test_add:281:garden-linux[8071]: uid/gid/perm /var/vcap/data/garden/aufs_graph/aufs/diff/99700f858b57772ec5a1b106aba258913b42ee84a98a80f1fda68156804f1dbd 4294967294/4294967294/0755, 0/0/0755
		[ 6670.389765] IPv6: ADDRCONF(NETDEV_UP): w5c4ev84eb0a-0: link is not ready
		[ 6670.389871] device w5c4ev84eb0a-0 entered promiscuous mode
		[ 6670.468180] device w5c4ev84eb0a-0 left promiscuous mode
		[ 6670.468224] wb-5c4ev84dv4a0: port 1(w5c4ev84eb0a-0) entered disabled state

Now i used back to garden version 316, btrfs filesystem is normal.In addition,Why do garden want to discard BTRFS? @ematpl

**Comment by wdxxs2z** [comment]
I found the error : the aufs filesystem mod is not added in the env. 

    cat /proc/filesystems | grep aufs

So,sudo modprobe aufs.

**Comment by julz** [comment]
Hi @wdxxs2z glad you found the problem! - The latest version of garden-linux uses aufs and this requires the aufs kernel module to be loaded. This is normally done dynamically by garden-linux, but when we're running in a container (e.g. in bosh-lite) we can't do this, so we need the host container engine needs to have done it. Bosh-lite is still running a slightly older version of garden-linux so it doesn't know how to do this yet. Once it upgrades to the latest garden-linux everything should work properly out of the box again. Sorry for the inconvenience in the meantime!
